---
name: CI
"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      foo_changed: ${{ steps.check.outputs.FOO_CHANGED }}
      bar_changed: ${{ steps.check.outputs.BAR_CHANGED }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/outputs
        id: check

  test:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      (needs.check.outputs.foo_changed == 'true' || needs.check.outputs.bar_changed == 'true')
    needs:
      - check
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo "Testing is done"
